# Initial import and setup #

In [1]:
import pandas as pd

try:
    df_matches = pd.read_csv("matches.csv")
    df_teams = pd.read_csv("teams.csv")
    df_venues = pd.read_csv("venues.csv")
    df_team_stats = pd.read_csv("match_team_stats.csv")
    df_squads_players = pd.read_csv("squads_and_players.csv")
    df_features = pd.read_csv("match_prediction_features.csv")

    print("Data Gathering Successful. All files loaded.")
except Exception as e:
    print(f"Error loading files: {e}")

Data Gathering Successful. All files loaded.

# Understanding initial data state #

## Visualizing data ##

In [2]:
print(f"- Matches: {df_matches.shape}")
display(df_matches.head())
print(f"- Teams: {df_teams.shape}")
display(df_teams.head())
print(f"- Venues: {df_venues.shape}")
display(df_venues.head())
print(f"- Team Stats: {df_team_stats.shape}")
display(df_team_stats.head())
print(f"- Squads & Players: {df_squads_players.shape}")
display(df_squads_players.head())
print(f"- Prediction Features: {df_features.shape}")
display(df_features.head())

- Matches: (104, 17)

,match_id,date,kickoff_time_utc,stage_id,venue_id,home_team_id,away_team_id,home_score,away_score,home_penalty_score,away_penalty_score,status,result_type,home_xg,away_xg,referee_id,player_of_the_match_id
0,1,2026-06-11,19:00,1,1,1,2,2,0,NaN,NaN,Completed,Regular,1.84,0.52,2,16
1,2,2026-06-11,23:00,1,7,3,4,2,1,NaN,NaN,Completed,Regular,1.45,1.12,9,58
2,3,2026-06-12,19:00,1,6,5,6,1,1,NaN,NaN,Completed,Regular,1.35,0.98,11,112
3,4,2026-06-12,23:00,1,3,13,14,4,1,NaN,NaN,Completed,Regular,2.76,0.88,12,332
4,5,2026-06-13,15:00,1,15,7,8,1,1,NaN,NaN,Completed,Regular,0.78,1.54,15,157

- Teams: (48, 8)

,team_id,team_name,fifa_code,group_letter,confederation,fifa_ranking_pre_tournament,elo_rating,manager_name
0,1,Mexico,MEX,A,CONCACAF,14,1810,Javier Aguirre
1,2,South Africa,RSA,A,CAF,60,1620,Hugo Broos
2,3,South Korea,KOR,A,AFC,22,1800,Hong Myung-bo
3,4,Czechia,CZE,A,UEFA,40,1740,Miroslav Koubek
4,5,Canada,CAN,B,CONCACAF,33,1795,Jesse Marsch

- Venues: (16, 8)

,venue_id,stadium_name,city,country,capacity,latitude,longitude,elevation_meters
0,1,Mexico City Stadium (Estadio Azteca),Mexico City,MEX,80824,19.3031,-99.1506,2200
1,2,New York New Jersey Stadium (MetLife Stadium),East Rutherford,USA,82500,40.8136,-74.0744,7
2,3,Los Angeles Stadium (SoFi Stadium),Inglewood,USA,70240,33.9535,-118.3390,30
3,4,Dallas Stadium (AT&T Stadium),Arlington,USA,80000,32.7473,-97.0928,184
4,5,Vancouver Stadium (BC Place),Vancouver,CAN,54500,49.2768,-123.1120,9

- Team Stats: (208, 12)

,match_id,team_id,possession_pct,total_shots,shots_on_target,corners,fouls,offsides,saves,player_of_the_match,data_source,last_updated
0,1,1,57,16,4,6,11,2,1,Julián Andrés Quinones,fifa.com,2026-06-24
1,1,2,43,3,2,3,15,1,4,NaN,fifa.com,2026-06-24
2,2,3,54,12,5,4,10,1,2,Inbeom Hwang,sofascore.com,2026-06-24
3,2,4,46,10,3,3,13,2,4,NaN,sofascore.com,2026-06-24
4,3,5,52,13,4,9,12,2,3,Ismaël Kenneth Jordan Kone,fifa.com,2026-06-24

- Squads & Players: (1248, 10)

,player_id,team_id,player_name,position,club_team,market_value_eur,caps,date_of_birth,height_cm,goals
0,1,1,José Raúl Rangel,GK,CD Guadalajara,8933646,15,2000-02-25,190,0
1,2,1,Jorge Eduardo Sanchez,DEF,PAOK Saloniki,24628639,59,1997-12-10,176,3
2,3,1,César Jasib Montes,DEF,FC Lokomotiv Moscow,10912552,69,1997-02-24,191,4
3,4,1,Edson Omar Alvarez,DEF,Fenerbahçe SK,10875943,100,1997-10-24,180,7
4,5,1,Johan Felipe Vasquez,DEF,Genoa CFC,18265363,47,1998-10-22,182,3

- Prediction Features: (104, 66)

,match_id,date,kickoff_time_utc,stage_id,is_knockout,home_team_id,home_team_name,home_fifa_code,home_confederation,away_team_id,...,home_prev_avg_xg_scored,home_prev_avg_xg_conceded,away_prev_avg_xg_scored,away_prev_avg_xg_conceded,home_score,away_score,result_type,home_xg,away_xg,match_result
0,1,2026-06-11,19:00,1,0,1,Mexico,MEX,CONCACAF,2,...,1.3,1.3,1.3,1.3,2,0,Regular,1.84,0.52,H
1,2,2026-06-11,23:00,1,0,3,South Korea,KOR,AFC,4,...,1.3,1.3,1.3,1.3,2,1,Regular,1.45,1.12,H
2,3,2026-06-12,19:00,1,0,5,Canada,CAN,CONCACAF,6,...,1.3,1.3,1.3,1.3,1,1,Regular,1.35,0.98,D
3,4,2026-06-12,23:00,1,0,13,USA,USA,CONCACAF,14,...,1.3,1.3,1.3,1.3,4,1,Regular,2.76,0.88,H
4,5,2026-06-13,15:00,1,0,7,Qatar,QAT,AFC,8,...,1.3,1.3,1.3,1.3,1,1,Regular,0.78,1.54,D

## Identifying missing values ##

In [3]:
print("\n Matches Missing Values")
display(df_matches.isnull().sum())

print("\n Teams Missing Values")
display(df_teams.isnull().sum())

print("\n Venues Missing Values")
display(df_venues.isnull().sum())

print("\n Team Stats Missing Values")
display(df_team_stats.isnull().sum())

print("\n Squads & Players Missing Values")
display(df_squads_players.isnull().sum())

print("\n Prediction Features Missing Values")
missing = df_features.isnull().sum()
if missing.sum() > 0:
    display(missing[missing_ > 0])
else:
    print("No missing values")

 Matches Missing Values

match_id                    0
date                        0
kickoff_time_utc            0
stage_id                    0
venue_id                    0
home_team_id                0
away_team_id                0
home_score                  0
away_score                  0
home_penalty_score        101
away_penalty_score        101
status                      0
result_type                 0
home_xg                     0
away_xg                     0
referee_id                  0
player_of_the_match_id      0
dtype: int64

 Teams Missing Values

team_id                        0
team_name                      0
fifa_code                      0
group_letter                   0
confederation                  0
fifa_ranking_pre_tournament    0
elo_rating                     0
manager_name                   0
dtype: int64

 Venues Missing Values

venue_id            0
stadium_name        0
city                0
country             0
capacity            0
latitude            0
longitude           0
elevation_meters    0
dtype: int64

 Team Stats Missing Values

match_id                 0
team_id                  0
possession_pct           0
total_shots              0
shots_on_target          0
corners                  0
fouls                    0
offsides                 0
saves                    0
player_of_the_match    104
data_source              0
last_updated             0
dtype: int64

 Squads & Players Missing Values

player_id           0
team_id             0
player_name         0
position            0
club_team           0
market_value_eur    0
caps                0
date_of_birth       0
height_cm           0
goals               0
dtype: int64

 Prediction Features Missing Values
No missing values

## Indentifying duplicates ##

In [4]:
print("\n Matches Duplicate Rows")
display(df_matches.duplicated().sum())

print("\n Teams Duplicate Rows")
display(df_teams.duplicated().sum())

print("\n Venues Duplicate Rows")
display(df_venues.duplicated().sum())

print("\n Team Stats Duplicate Rows")
display(df_team_stats.duplicated().sum())

print("\n Squads & Players Duplicate Rows")
display(df_squads_players.duplicated().sum())

print("\n Prediction Features Duplicate Rows")
display(df_features.duplicated().sum())

 Matches Duplicate Rows

np.int64(0)

 Teams Duplicate Rows

np.int64(0)

 Venues Duplicate Rows

np.int64(0)

 Team Stats Duplicate Rows

np.int64(0)

 Squads & Players Duplicate Rows

np.int64(0)

 Prediction Features Duplicate Rows

np.int64(0)

# Data Cleaning #
## Dropping all irrelavant data ##

In [5]:
df_matches_cleaned = df_matches.drop(
    columns=['referee_id', 'player_of_the_match_id', 'status', 'kickoff_time_utc']
).copy() 

df_teams_cleaned = df_teams.drop(
    columns=['manager_name']
).copy() 

df_venues_cleaned = df_venues.drop(
    columns=['capacity']
).copy()

df_team_stats_cleaned = df_team_stats.drop(
    columns=['data_source', 'last_updated', 'player_of_the_match']
).copy() 

df_squads_players_cleaned = df_squads_players.drop(
    columns=['club_team', 'date_of_birth', 'height_cm']
).copy() 

df_features_cleaned = df_features.drop(
    columns=['referee_id', 'referee_name', 'kickoff_time_utc']
).copy()

# Uncomment to see retained columns 
# display(df_features_cleaned.columns.tolist())
# display(df_squads_players_cleaned.columns.tolist())
# display(df_team_stats_cleaned.columns.tolist())
# display(df_venues_cleaned.columns.tolist())
# display(df_teams_cleaned.columns.tolist())
# display(df_matches_cleaned.columns.tolist())

## Handling missing values in Matches dataset ##

In [6]:
# these 2 columns record how many scores each team (home or away) has for penalty shootout
# which does not happen when a match has a winner by the end of time 
# We cannot just drop them or fill in with anything rather than a zero otherwise it would skew the dataset 

df_matches_cleaned['home_penalty_score'] = df_matches_cleaned['home_penalty_score'].fillna(0).astype(int)
df_matches_cleaned['away_penalty_score'] = df_matches_cleaned['away_penalty_score'].fillna(0).astype(int)

# verify to check there is no NaN left
display(df_matches_cleaned.isnull().sum())

match_id              0
date                  0
stage_id              0
venue_id              0
home_team_id          0
away_team_id          0
home_score            0
away_score            0
home_penalty_score    0
away_penalty_score    0
result_type           0
home_xg               0
away_xg               0
dtype: int64

# Data Aggregation and Analysis #
## Team performance comparison based on different metrics (goals scored, possession, card distribution etc) ##

In [7]:
# combine the relavant datasets into one
df_obj_A = pd.merge(df_team_stats_cleaned, df_teams_cleaned[['team_id', 'team_name']], on='team_id', how='inner')
df_obj_A = pd.merge(df_obj_A, df_matches_cleaned[['match_id', 'result_type']], on='match_id', how='inner')

# calculate the average per match for each team 
team_avg = df_obj_A.groupby('team_name')[
    ['possession_pct', 'shots_on_target', 'fouls', 'saves']
].mean().reset_index()

display(team_avg.head())
display(team_avg.tail())

# possession control
best_possession = team_avg.loc[team_avg['possession_pct'].idxmax()]
worst_possession = team_avg.loc[team_avg['possession_pct'].idxmin()]

# attacking threat
best_attack = team_avg.loc[team_avg['shots_on_target'].idxmax()]
worst_attack = team_avg.loc[team_avg['shots_on_target'].idxmin()]

# discipline
most_fouls = team_avg.loc[team_avg['fouls'].idxmax()]
cleanest = team_avg.loc[team_avg['fouls'].idxmin()]

# defensive  
most_saves = team_avg.loc[team_avg['saves'].idxmax()]
fewest_saves = team_avg.loc[team_avg['saves'].idxmin()]

print("Team Performance")
print(f"- Possession: Highest = {best_possession['team_name']} ({best_possession['possession_pct']}%) | Lowest = {worst_possession['team_name']} ({worst_possession['possession_pct']}%)")
print(f"- Attack: Highest = {best_attack['team_name']} ({best_attack['shots_on_target']}) | Lowest = {worst_attack['team_name']} ({worst_attack['shots_on_target']})")
print(f"- Discipline: Most Fouls = {most_fouls['team_name']} ({most_fouls['fouls']}) | Fewest = {cleanest['team_name']} ({cleanest['fouls']})")
print(f"- Saves: Highest = {most_saves['team_name']} ({most_saves['saves']}) | Lowest = {fewest_saves['team_name']} ({fewest_saves['saves']})")

   team_name  possession_pct  shots_on_target      fouls  saves
0    Algeria       56.750000         3.500000   8.000000   2.00
1  Argentina       57.875000         6.125000  10.250000   2.00
2  Australia       38.750000         3.500000  12.000000   2.75
3    Austria       46.250000         2.000000  11.750000   3.00
4    Belgium       55.666667         6.666667  12.333333   2.50

     team_name  possession_pct  shots_on_target      fouls     saves
43     Tunisia       42.333333         2.000000   9.333333  4.333333
44     Türkiye       59.000000         6.333333   9.666667  2.333333
45         USA       51.200000         3.600000  10.600000  2.400000
46     Uruguay       56.666667         6.666667  10.000000  3.000000
47  Uzbekistan       35.666667         1.333333  14.000000  3.333333

Team Performance
- Possession: Highest = Germany (63.5%) | Lowest = Paraguay (27.8%)
- Attack: Highest = Germany (8.25) | Lowest = Iraq (0.6666666666666666)
- Discipline: Most Fouls = Canada (14.2) | Fewest = Cabo Verde (7.0)
- Saves: Highest = Curaçao (8.333333333333334) | Lowest = Canada (1.4)

## Player and squad market valuation analysis ##

In [8]:
# merge player data with team names
df_squad_valuation = pd.merge(df_squads_players_cleaned, df_teams_cleaned[['team_id', 'team_name']], on='team_id', how='inner')

# calculate the Total Squad Value 
squad_financials = df_squad_valuation.groupby('team_name')[['market_value_eur']].sum().reset_index()
squad_financials = squad_financials.rename(columns={'market_value_eur': 'total_value'})

# calculate the Average Player Value 
squad_avg = df_squad_valuation.groupby('team_name')[['market_value_eur']].mean().reset_index()

# add the averages into main financials table
squad_financials['avg_player_value'] = squad_avg['market_value_eur']

# the most and least valuable squads
most_valuable_squad = squad_financials.loc[squad_financials['total_value'].idxmax()]
least_valuable_squad = squad_financials.loc[squad_financials['total_value'].idxmin()]

# the single most valuable player in the tournament
most_valuable_player = df_squad_valuation.loc[df_squad_valuation['market_value_eur'].idxmax()]

print("Market Valuation")
print(f"- Total Squad Value: Highest = {most_valuable_squad['team_name']} (€{most_valuable_squad['total_value']}) | Lowest = {least_valuable_squad['team_name']} (€{least_valuable_squad['total_value']})")
print(f"- Avg Player Value: Highest = {most_valuable_squad['team_name']} (€{most_valuable_squad['avg_player_value']}) | Lowest = {least_valuable_squad['team_name']} (€{least_valuable_squad['avg_player_value']})")
print(f"- Most Valuable Player: {most_valuable_player['player_name']} ({most_valuable_player['team_name']}) at €{most_valuable_player['market_value_eur']}")

print("\n Top 5 Most Valuable Squads")
display(squad_financials.sort_values(by='total_value', ascending=False).head())

Market Valuation
- Total Squad Value: Highest = Spain (€2134173029) | Lowest = New Zealand (€37905696)
- Avg Player Value: Highest = Spain (€82083578.03846154) | Lowest = New Zealand (€1457911.3846153845)
- Most Valuable Player: Lamine Yamal Yamal (Spain) at €200000000

 Top 5 Most Valuable Squads

    team_name  total_value  avg_player_value
40      Spain   2134173029      8.208358e+07
18     France   1546204469      5.946940e+07
17    England   1321818896      5.083919e+07
33   Portugal   1145908765      4.407341e+07
1   Argentina   1025039444      3.942459e+07

## How do stadium elevation and location affect match tempo or fatigue? ##

In [9]:
import requests

weather_records = []

# get elevation and typical tournament weather for each stadium
for index, venue in df_venues_cleaned.iterrows():
    lat = venue['latitude']
    lon = venue['longitude']
    venue_id = venue['venue_id']

    # pulling elevation and forecast/daily temperatures from Open Meteo API
    url = f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&daily=temperature_2m_max,apparent_temperature_max&timezone=auto"
    
    response = requests.get(url)
    data = response.json()
    
    # extract elevation from the API 
    api_elevation = data.get('elevation')
    
    # extract average daily max and feels-like temperature
    daily_temps = data['daily']['temperature_2m_max']
    daily_feels_like = data['daily']['apparent_temperature_max']
    
    avg_temp = sum(daily_temps) / len(daily_temps)
    avg_feels_like = sum(daily_feels_like) / len(daily_feels_like)
    
    # store in records list
    weather_records.append({
        'venue_id': venue_id,
        'elevation_m': api_elevation,
        'avg_temp': avg_temp,
        'avg_feels_like': avg_feels_like
    })

# convert the API data to a dataframe
df_open_meteo = pd.DataFrame(weather_records)

print("Open-Meteo API Results")
display(df_open_meteo.head())

Open-Meteo API Results

   venue_id  elevation_m   avg_temp  avg_feels_like
0         1       2245.0  20.757143       22.871429
1         2          4.0  20.857143       19.742857
2         3         44.0  24.428571       23.557143
3         4        198.0  31.657143       32.485714
4         5         18.0  14.485714       12.485714

In [10]:
# add to venues with Open Meteo data
df_venues_plus = pd.merge(df_venues_cleaned, df_open_meteo, on='venue_id', how='inner')

# link matches to venues
df_matches_env = pd.merge(df_matches_cleaned[['match_id', 'venue_id']], df_venues_plus, on='venue_id', how='inner')

# combine with team performance metrics (tempo = shots, fatigue = fouls)
df_obj_C = pd.merge(df_team_stats_cleaned, df_matches_env, on='match_id', how='inner')

# group by venue to calculate average match attributes with environmental factors
venue_summary = df_obj_C.groupby(['stadium_name', 'city', 'elevation_m', 'avg_temp', 'avg_feels_like'])[
    ['total_shots', 'shots_on_target', 'fouls']
].mean().reset_index()

print("Venue Summary Dataset (Venues + Weather + Match Stats)")
display(venue_summary.head())

Venue Summary Dataset (Venues + Weather + Match Stats)

,stadium_name,city,elevation_m,avg_temp,avg_feels_like,total_shots,shots_on_target,fouls
0,Atlanta Stadium (Mercedes-Benz Stadium),Atlanta,314.0,28.442857,29.114286,12.750000,4.437500,10.812500
1,Boston Stadium (Gillette Stadium),Foxborough,89.0,17.114286,15.400000,11.642857,3.928571,11.000000
2,Dallas Stadium (AT&T Stadium),Arlington,198.0,31.657143,32.485714,12.111111,4.388889,10.277778
3,Guadalajara Stadium (Estadio Akron),Zapopan,1673.0,22.014286,23.714286,10.375000,3.125000,10.750000
4,Houston Stadium (NRG Stadium),Houston,32.0,32.814286,34.928571,12.062500,4.625000,11.062500

In [18]:
# elevation extremes
highest_alt = venue_summary.loc[venue_summary['elevation_m'].idxmax()]
lowest_alt = venue_summary.loc[venue_summary['elevation_m'].idxmin()]

# temperature extremes
hottest_venue = venue_summary.loc[venue_summary['avg_temp'].idxmax()]
coldest_venue = venue_summary.loc[venue_summary['avg_temp'].idxmin()]

# tempo and fatigue extremes
highest_tempo = venue_summary.loc[venue_summary['total_shots'].idxmax()]
lowest_tempo = venue_summary.loc[venue_summary['total_shots'].idxmin()]
most_fouls = venue_summary.loc[venue_summary['fouls'].idxmax()]
cleanest_venue = venue_summary.loc[venue_summary['fouls'].idxmin()]

print("Environmental & Match Extremes\n")

print(f"Elevation: Highest = {highest_alt['stadium_name']} ({highest_alt['elevation_m']}m) | Lowest = {lowest_alt['stadium_name']} ({lowest_alt['elevation_m']}m)")
print(f"Climate: Hottest = {hottest_venue['stadium_name']} ({hottest_venue['avg_temp']}°C) | Coolest = {coldest_venue['stadium_name']} ({coldest_venue['avg_temp']}°C)")
print(f"Match tempo: Highest = {highest_tempo['stadium_name']} ({highest_tempo['total_shots']} shots/game) | Lowest = {lowest_tempo['stadium_name']} ({lowest_tempo['total_shots']} shots/game)")
print(f"Fatigue indicator: Most Fouls = {most_fouls['stadium_name']} ({most_fouls['fouls']} fouls/game) | Fewest = {cleanest_venue['stadium_name']} ({cleanest_venue['fouls']} fouls/game)")

Environmental & Match Extremes

Elevation: Highest = Mexico City Stadium (Estadio Azteca) (2245.0m) | Lowest = Philadelphia Stadium (Lincoln Financial Field) (0.0m)
Climate: Hottest = Houston Stadium (NRG Stadium) (32.81428571428571°C) | Coolest = Vancouver Stadium (BC Place) (14.485714285714286°C)
Match tempo: Highest = Miami Stadium (Hard Rock Stadium) (14.3125 shots/game) | Lowest = Guadalajara Stadium (Estadio Akron) (10.375 shots/game)
Fatigue indicator: Most Fouls = Seattle Stadium (Lumen Field) (12.125 fouls/game) | Fewest = Miami Stadium (Hard Rock Stadium) (10.0 fouls/game)

## Association of match outcomes using FIFA rankings, rolling form, and team strength etc ##